-- ============================================================
-- SETUP SUPABASE UNTUK TUGASKU
-- Jalankan seluruh isi file ini di: Supabase Dashboard -> SQL Editor -> New query -> Run
-- ============================================================

-- 1. Tabel utama untuk menyimpan data tugas
create table if not exists tugas (
  id bigint generated by default as identity primary key,
  judul text not null,
  tipe text not null check (tipe in ('file', 'link')),
  value text not null,       -- nama file (jika tipe=file) atau URL (jika tipe=link)
  file_path text,            -- path file di storage (khusus tipe=file)
  waktu timestamptz not null default now()
);

-- 2. Aktifkan Row Level Security
alter table tugas enable row level security;

-- 3. Izinkan semua orang (anon) untuk baca, tambah, dan hapus data
--    Catatan: ini setara dengan aplikasi Java aslinya yang tidak pakai login.
--    Kalau nanti mau ditambah login dosen/mahasiswa, policy ini perlu diperketat.
create policy "Semua bisa lihat tugas" on tugas
  for select using (true);

create policy "Semua bisa tambah tugas" on tugas
  for insert with check (true);

create policy "Semua bisa hapus tugas" on tugas
  for delete using (true);

-- 4. Buat bucket storage untuk file upload (PDF, DOC, DOCX, ZIP)
insert into storage.buckets (id, name, public)
values ('files', 'files', true)
on conflict (id) do nothing;

-- 5. Izinkan upload & hapus file di bucket 'files'
create policy "Semua bisa upload file tugas" on storage.objects
  for insert with check (bucket_id = 'files');

create policy "Semua bisa lihat file tugas" on storage.objects
  for select using (bucket_id = 'files');

create policy "Semua bisa hapus file tugas" on storage.objects
  for delete using (bucket_id = 'files');
